apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
spec:
  ports:
    - port: 2181
      name: client
    - port: 7000
      name: prometheus
  selector:
    {{- include "clickhouse-keeper.selectorLabels" . | nindent 4 }}
