# Copyright (c) 2023 VEXXHOST, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# State of the Magnum auto healer service
magnum_auto_healer_state: present

# Path to the KUBECONFIG file to use for the Kubernetes API
# magnum_auto_healer_cluster_kubeconfig:

# Cluster network ID to be run commands against the cluster (since it can be
# isolated from the control plane).
# magnum_auto_healer_cluster_network_id:
