replicaCount: 3

image:
  repository: clickhouse/clickhouse-keeper
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # requests:
  #   memory: "256M"
  #   cpu: "1"
  # limits:
  #   memory: "4Gi"
  #   cpu: "2"

nodeSelector:
  openstack-control-plane: enabled

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClassName: general
  accessModes:
    - ReadWriteOnce
  size: 25Gi
