- name: Update "magnum-auto-healer" DaemonSet
  become: true
  run_once: true
  delegate_to: "{{ magnum_auto_healer_cluster_network_host }}"
  ansible.builtin.command:
    ip netns exec qdhcp-{{ magnum_auto_healer_cluster_network_id }} \
      kubectl patch daemonset/magnum-auto-healer \
        -n kube-system  \
        -p '{{ patch | to_json }}'
  environment:
    KUBECONFIG: "{{ magnum_auto_healer_cluster_kubeconfig }}"
  vars:
    patch:
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/master: "{% if magnum_auto_healer_state == 'absent' %}maintenance{% endif %}"
