- name: Update "magnum-auto-healer" DaemonSet
  become: true
  run_once: true
  delegate_to: "{{ magnum_auto_healer_cluster_network_host }}"
  ansible.builtin.command:
    ip netns exec qdhcp-{{ magnum_auto_healer_cluster_network_id }} \
      kubectl patch daemonset/magnum-auto-healer \
        --namespace kube-system \
        -p '{{ patch | to_json }}'
  register: _magnum_auto_healer_patch
  changed_when: _magnum_auto_healer_patch.rc == 0 and 'no change' not in _magnum_auto_healer_patch.stdout
  environment:
    KUBECONFIG: "{{ magnum_auto_healer_cluster_kubeconfig }}"
  vars:
    patch:
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/master: "{% if magnum_auto_healer_state == 'absent' %}maintenance{% endif %}"
