- name: Update "magnum-auto-healer" DaemonSet
  become: true
  become_method: sudo
  become_flags: "ip netns exec qdhcp-{{ magnum_auto_healer_cluster_network_id }}"
  delegate_to: "{{ magnum_auto_healer_cluster_network_host }}"
  kubernetes.core.k8s:
    state: patched
    kind: DaemonSet
    namespace: kube-system
    name: magnum-auto-healer
    definition:
      spec:
        template:
          spec:
            nodeSelector:
              node-role.kubernetes.io/master: "{% if magnum_auto_healer_state == 'absent' %}maintenance{% endif %}"
  environment:
    KUBECONFIG: "{{ magnum_auto_healer_cluster_kubeconfig }}"
